#!/bin/bash

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y python3 python3-pip python3-venv python3.13-dev
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm python python-pip python-virtualenv
fi

cd $(dirname "$AUDITON_PATH")
sudo git clone https://github.com/RefazSaleem/Auditon
sudo chown -R $USER:$SERVER_GROUP "$AUDITON_PATH"
cd "$AUDITON_PATH"

if [ ! -d "$AUDITON_VENV" ]; then
  $PYVER -m venv "$AUDITON_VENV"
fi
mkdir -p $AUDITON_DB_PATH

source "$AUDITON_VENV/bin/activate"
pip install --upgrade pip
pip install -r requirements.txt

cat <<EOF | tee "$AUDITON_CONF" > /dev/null
host = $HOST_IP
port = $AUDITON_PORT
logfile = $AUDITON_LOG
database_folder = $AUDITON_DB_PATH
secret_key = auditon-secret
session_timeout_days = 7
EOF

cat > "$AUDITON_START_SCRIPT" <<EOL
#!/bin/bash
source "$AUDITON_VENV/bin/activate"
$PYVER $AUDITON_PATH/main.py
EOL
chmod +x "$AUDITON_START_SCRIPT"

cat <<EOF | sudo tee "$AUDITON_SERVICE" > /dev/null
[Unit]
Description=Auditon Service
After=network.target

[Service]
ExecStart=$AUDITON_START_SCRIPT
WorkingDirectory=$AUDITON_PATH
User=$USER
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now $(basename $AUDITON_SERVICE .service)

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$AUDITON_CADDY_CONF" > /dev/null <<EOF
https://$TS_DN:$((AUDITON_PORT - 10000)) {
    reverse_proxy $HOST_IP:$AUDITON_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((AUDITON_PORT - 10001)) {
    reverse_proxy $HOST_IP:$AUDITON_PORT
}

EOF
        sudo chown -R caddy:caddy $AUDITON_CADDY_CONF
        sudo chmod -R 755 $AUDITON_CADDY_CONF
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$AUDITON_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: Auditon
        url: "https://$TS_DN:$((AUDITON_PORT - 10000))"
        subtitle: Budget Tracker
        icon: "fas fa-wallet"
Unsecure
      - name: Auditon
        url: "http://$TS_HOST:$((AUDITON_PORT - 10001))"
        subtitle: Budget Tracker
        icon: "fas fa-wallet"
EOF
        sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
        sudo chmod -R 755 $HOMER_MODULES_DIR
else
    echo "Homer not installed — skipping"
fi


echo "Auditon service has been installed and configured successfully!"
