#!/bin/bash
source ./.variables

sudo mkdir -p "$BESZELHUB_PATH"
sudo curl -sL "${GITHUB_PROXY_URL}https://github.com/henrygd/beszel/releases/latest/download/beszel_$(uname -s)_$(uname -m | sed 's/x86_64/amd64/' | sed 's/armv7l/arm/' | sed 's/aarch64/arm64/').tar.gz" | sudo tar -xz -C "$BESZELHUB_PATH" beszel
sudo chmod +x "$BESZELHUB_PATH/beszel"
sudo mkdir -p "$BESZELHUB_PATH/beszel_data"
sudo chown -R $USER:$SERVER_GROUP $BESZELHUB_PATH

cat <<EOF | sudo tee -a "$BESZELHUB_SERVICE" > /dev/null
[Unit]
Description=Beszel Hub Service
After=network.target

[Service]
ExecStart=$BESZELHUB_PATH/beszel serve --http "0.0.0.0:$BESZELHUB_PORT"
WorkingDirectory=$BESZELHUB_PATH
User=$USER
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

cat <<EOF | sudo tee -a "$BESZELHUB_UPDATE" > /dev/null
[Unit]
Description=Update beszel-hub if needed
Wants=beszel-hub.service

[Service]
Type=oneshot
ExecStart=$BESZELHUB_PATH/beszel update

[Install]
WantedBy=multi-user.target
EOF

cat <<EOF | sudo tee -a "$BESZELHUB_UP_TIMER" > /dev/null
[Unit]
Description=Run beszel-hub update daily

[Timer]
OnCalendar=daily
Persistent=true
RandomizedDelaySec=4h

[Install]
WantedBy=timers.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now "$BESZELHUB_SERVICE" "$BESZELHUB_UPDATE" "$BESZELHUB_UP_TIMER"

cat <<EOF | sudo tee -a "$CADDY_CONF" > /dev/null
http://$TS_HOST:$((BESZELHUB_PORT - 12001)) {
    reverse_proxy $HOST_IP:$BESZELHUB_PORT
}

https://$TS_DN:$((BESZELHUB_PORT - 12000)) {
    reverse_proxy $HOST_IP:$BESZELHUB_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
EOF
sudo systemctl restart caddy

echo "The Beszel Hub has been installed and configured successfully! It is now accessible on port $BESZELHUB_PORT."
