#!/bin/bash

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    VERSION="trixie"
    sudo apt install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: ${VERSION}
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm docker docker-compose
fi

sudo systemctl enable --now docker

mkdir -p "$BUDGETBEE_BASE_DIR"

cat > "$BUDGETBEE_ENV_FILE" << EOF
APP_ENV=production
APP_DEBUG=false
HOST=$HOST_IP
APP_PORT=$BUDGETBEE_PORT
DB_CONNECTION=mysql
DB_HOST=$HOST_IP
DB_DATABASE=budgetbee
DB_USERNAME=budgetbee
DB_PASSWORD=budgetbee
DB_ROOT_PASSWORD=root_budgetbee
EOF

cat > "$BUDGETBEE_COMPOSE_FILE" << 'EOF'
services:
  nginx:
    image: ghcr.io/budgetbee/budgetbee/proxy:latest
    command: nginx -g "daemon off;"
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - webserver
      - web
    restart: unless-stopped
    networks:
      - skynet
  webserver:
    image: ghcr.io/budgetbee/budgetbee/api:latest
    working_dir: /var/www/html
    command: sh entrypoint.sh
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - skynet
  web:
    image: ghcr.io/budgetbee/budgetbee/web:latest
    restart: unless-stopped
    networks:
      - skynet
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=${DB_USERNAME}",  "--password=${DB_PASSWORD}", "--execute", "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB_DATABASE}';"]
      timeout: 20s
      retries: 100
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skynet
networks:
  skynet:
volumes:
  db_data:
EOF


cd "$BUDGETBEE_BASE_DIR"
sudo docker compose up -d

cat <<'EOF' | sudo tee "$BUDGETBEE_SIGNUP" > /dev/null
#!/bin/bash
read -p "Enter email: " email
read -p "Enter name: " name
read -s -p "Enter password: " password
echo
echo "Creating superuser with:"
echo "  Name: $name"
echo "  Email: $email"
sudo docker exec budgetbee-webserver-1 php scripts/create_user.php "$name" "$email" "$password"
EOF

sudo chmod +x "$BUDGETBEE_SIGNUP"

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$BUDGETBEE_CADDY_CONF" > /dev/null <<EOF
https://$TS_DN:$((BUDGETBEE_PORT - 10000)) {
    reverse_proxy $HOST_IP:$BUDGETBEE_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((BUDGETBEE_PORT - 10001)) {
    reverse_proxy $HOST_IP:$BUDGETBEE_PORT
}

EOF
        sudo chown -R caddy:caddy $BUDGETBEE_CADDY_CONF
        sudo chmod -R 755 $BUDGETBEE_CADDY_CONF
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$BUDGETBEE_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: BudgetBee
        url: "https://$TS_DN:$((BUDGETBEE_PORT - 10000))"
        subtitle: Budget Tracker
        icon: "fas fa-wallet"
Unsecure
      - name: BudgetBee
        url: "http://$TS_HOST:$((BUDGETBEE_PORT - 10001))"
        subtitle: Budget Tracker
        icon: "fas fa-wallet"
EOF
        sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
        sudo chmod -R 755 $HOMER_MODULES_DIR
else
    echo "Homer not installed — skipping"
fi

echo "BudgetBee service has been installed and configured successfully!"
