#!/bin/bash

source ./.variables

mkdir -p "$BUDGETBEE_BASE_DIR"

cat > "$BUDGETBEE_ENV_FILE" << EOF
APP_ENV=production
APP_DEBUG=false
HOST=$HOST_IP
APP_PORT=$BUDGETBEE_PORT
DB_CONNECTION=mysql
DB_HOST=$HOST_IP
DB_DATABASE=budgetbee
DB_USERNAME=budgetbee
DB_PASSWORD=budgetbee
DB_ROOT_PASSWORD=root_budgetbee
EOF

cat > "$BUDGETBEE_COMPOSE_FILE" << 'EOF'
services:
  nginx:
    image: ghcr.io/budgetbee/budgetbee/proxy:latest
    command: nginx -g "daemon off;"
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - webserver
      - web
    restart: unless-stopped
    networks:
      - skynet
  webserver:
    image: ghcr.io/budgetbee/budgetbee/api:latest
    working_dir: /var/www/html
    command: sh entrypoint.sh
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - skynet
  web:
    image: ghcr.io/budgetbee/budgetbee/web:latest
    restart: unless-stopped
    networks:
      - skynet
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=${DB_USERNAME}",  "--password=${DB_PASSWORD}", "--execute", "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '${DB_DATABASE}';"]
      timeout: 20s
      retries: 100
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - skynet
networks:
  skynet:
volumes:
  db_data:
EOF


cd "$BUDGETBEE_BASE_DIR"
sudo docker compose up -d

cat <<'EOF' | sudo tee -a "$BUDGETBEE_SIGNUP" > /dev/null
#!/bin/bash
read -p "Enter email: " email
read -p "Enter name: " name
read -s -p "Enter password: " password
echo
echo "Creating superuser with:"
echo "  Name: $name"
echo "  Email: $email"
sudo docker exec budgetbee-webserver-1 php scripts/create_user.php "$name" "$email" "$password"
EOF

sudo chmod +x "$BUDGETBEE_SIGNUP"

cat <<EOF | sudo tee -a "$CADDY_CONF" > /dev/null
http://$TS_HOST:$((BUDGETBEE_PORT - 10001)) {
    reverse_proxy $HOST_IP:$BUDGETBEE_PORT
}

https://$TS_DN:$((BUDGETBEE_PORT - 10000)) {
    reverse_proxy $HOST_IP:$BUDGETBEE_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}

EOF
sudo systemctl restart caddy