#!/bin/sh

source ./.variables

mkdir -p "$ESPHOME_BASE_DIR"
mkdir -p "$ESPHOME_CONF_DIR"

cat > "$ESPHOME_COMPOSE_FILE" << EOF
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - $ESPHOME_CONF_DIR:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: bridge
    ports:
      - "$ESPHOME_PORT:6052"
EOF

cd "$ESPHOME_BASE_DIR"
sudo docker compose up -d

cat <<EOF | sudo tee -a "$CADDY_CONF" > /dev/null
http://$TS_HOST:$((ESPHOME_PORT - 10001)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
}

https://$TS_DN:$((ESPHOME_PORT - 10000)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}

EOF

sudo systemctl restart caddy