#!/bin/bash
source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y python3 python3-pip python3-venv build-essential ffmpeg git libpcap0.8
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm python python-pip python-virtualenv base-devel ffmpeg git libpcap
fi

if [ ! -d "$ESPHOME_VENV_PATH" ]; then
  $PYVER -m venv "$ESPHOME_VENV_PATH"
fi

source "$ESPHOME_VENV_PATH/bin/activate"
pip install --upgrade pip
pip install esphome

mkdir -p "$ESPHOME_SCRIPT_PATH" "$ESPHOME_CONFIG_PATH"

cat > "$ESPHOME_SCRIPT_PATH/esphome" <<EOL
#!/bin/bash
source "$ESPHOME_VENV_PATH/bin/activate"
exec $PYVER -m esphome dashboard $ESPHOME_CONFIG_PATH --port $ESPHOME_PORT --address $HOST_IP
EOL
chmod +x "$ESPHOME_SCRIPT_PATH/esphome"

cat <<EOF | sudo tee -a "$ESPHOME_SERVICE" > /dev/null
[Unit]
Description=ESP Home
After=network-online.target

[Service]
Type=simple
ExecStart=$ESPHOME_SCRIPT_PATH/esphome
Restart=on-failure
User=$USER
RestartSec=5s

[Install]
WantedBy=default.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now esphome

echo "ESPHome has been set up and started as a systemd service."
