#!/bin/sh

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y docker docker-compose 
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm docker docker-compose
fi

sudo systemctl enable --now docker
mkdir -p "$ESPHOME_BASE_DIR"
mkdir -p "$ESPHOME_CONF_DIR"

cat > "$ESPHOME_COMPOSE_FILE" << EOF
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - $ESPHOME_CONF_DIR:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: bridge
    ports:
      - "$ESPHOME_PORT:6052"
EOF

cd "$ESPHOME_BASE_DIR"
sudo docker compose up -d

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$ESPHOME_CADDY_CONF" > /dev/null <<EOF

https://$TS_DN:$((ESPHOME_PORT - 10000)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((ESPHOME_PORT - 10001)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
}

EOF
	sudo chown -R caddy:caddy $CADDY_SITES
	sudo chmod -R 755 $CADDY_SITES
	sudo systemctl restart caddy
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$ESPHOME_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: ESPHome
        url: "https://$TS_DN:$((ESPHOME_PORT - 10000))"
        subtitle: Home Automation
        icon: "fas fa-microchip"
Unsecure
      - name: ESPHome
        url: "http://$TS_HOST:$((ESPHOME_PORT - 10001))"
        subtitle: Home Automation
        icon: "fas fa-microchip"
EOF
	sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
	sudo chmod -R 755 $HOMER_MODULES_DIR
	sudo bash $HOMER_UPDATE_SCRIPT
	sudo systemctl restart homer
else
    echo "Homer not installed — skipping"
fi


echo "ESPHome service has been installed and configured successfully!"
