#!/bin/sh

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    VERSION="trixie"
    sudo apt install ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings
    sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    sudo tee /etc/apt/sources.list.d/docker.sources <<EOF
Types: deb
URIs: https://download.docker.com/linux/debian
Suites: "$VERSION"
Components: stable
Signed-By: /etc/apt/keyrings/docker.asc
EOF
    sudo apt update
    sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm docker docker-compose
fi

sudo systemctl enable --now docker
mkdir -p "$ESPHOME_BASE_DIR"
mkdir -p "$ESPHOME_CONF_DIR"

cat > "$ESPHOME_COMPOSE_FILE" << EOF
services:
  esphome:
    container_name: esphome
    image: esphome/esphome
    volumes:
      - $ESPHOME_CONF_DIR:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: bridge
    ports:
      - "$ESPHOME_PORT:6052"
EOF

cd "$ESPHOME_BASE_DIR"
sudo docker compose up -d

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$ESPHOME_CADDY_CONF" > /dev/null <<EOF

https://$TS_DN:$((ESPHOME_PORT - 10000)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((ESPHOME_PORT - 10001)) {
    reverse_proxy $HOST_IP:$ESPHOME_PORT
}

EOF
	sudo chown -R caddy:caddy $ESPHOME_CADDY_CONF
	sudo chmod -R 755 $ESPHOME_CADDY_CONF
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$ESPHOME_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: ESPHome
        url: "https://$TS_DN:$((ESPHOME_PORT - 10000))"
        subtitle: Home Automation
        icon: "fas fa-microchip"
Unsecure
      - name: ESPHome
        url: "http://$TS_HOST:$((ESPHOME_PORT - 10001))"
        subtitle: Home Automation
        icon: "fas fa-microchip"
EOF
	sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
	sudo chmod -R 755 $HOMER_MODULES_DIR
else
    echo "Homer not installed — skipping"
fi


echo "ESPHome service has been installed and configured successfully!"
