#!/bin/sh

source ./.variables

mkdir -p "$HASS_BASE_DIR"
mkdir -p "$HASS_CONF_DIR"

cat > "$HASS_COMPOSE_FILE" << EOF
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - $HASS_CONF_DIR:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - "$HASS_PORT:8123"
EOF

cd "$HASS_BASE_DIR"
sudo docker compose up -d
PROXY_RANGE=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' homeassistant | awk -F. '{print $1"."$2".0.0/16"}')

cat <<EOF | sudo tee -a "$HASS_CONF_DIR/configuration.yaml" > /dev/null
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - $PROXY_RANGE

EOF

cat <<EOF | sudo tee -a "$CADDY_CONF" > /dev/null
http://$TS_HOST:$((HASS_PORT - 10001)) {
    reverse_proxy $HOST_IP:$HASS_PORT
}

https://$TS_DN:$((HASS_PORT - 10000)) {
    reverse_proxy $HOST_IP:$HASS_PORT
    encode gzip
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}

EOF

sudo systemctl restart caddy