#!/bin/bash
source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y python3 python3-pip python3-venv build-essential ffmpeg git libpcap0.8 libpq-dev coturn openssl libssl-dev curl
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm jellyfin-server jellyfin-web
fi
sudo systemctl enable --now jellyfin
sudo mkdir -p "$JELLYFIN_DIR"
sudo usermod -aG $SERVER_GROUP jellyfin
sudo chown -R :$SERVER_GROUP "$JELLYFIN_DIR"
sudo find "$JELLYFIN_DIR" -type f -exec chmod 660 {} \;
sudo find "$JELLYFIN_DIR" -type d -exec chmod 770 {} \;

cat <<EOF | sudo tee "$JELLYFIN_MEDIA_PERM_SCRIPT" > /dev/null
#!/bin/bash
sudo chown -R :$SERVER_GROUP $JELLYFIN_DIR
sudo find "$JELLYFIN_DIR" -type f -exec chmod 660 {} \;
sudo find "$JELLYFIN_DIR" -type d -exec chmod 770 {} \;
EOF

sudo chmod +x "$JELLYFIN_MEDIA_PERM_SCRIPT"

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$JELLYFIN_CADDY_CONF" > /dev/null <<EOF
https://$TS_DN:$((JELLYFIN_PORT + 327)) {
    reverse_proxy $HOST_IP:$JELLYFIN_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((JELLYFIN_PORT + 326)) {
    reverse_proxy $HOST_IP:$JELLYFIN_PORT
}

EOF
	sudo chown -R caddy:caddy $CADDY_SITES
	sudo chmod -R 755 $CADDY_SITES
	sudo systemctl restart caddy
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$JELLYFIN_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: Jellyfin
        url: "https://$TS_DN:$((JELLYFIN_PORT + 327))"
        subtitle: Media Server
        icon: "fas fa-tv"
Unsecure
      - name: Jellyfin
        url: "http://$TS_HOST:$((JELLYFIN_PORT + 326))"
        subtitle: Media Server
        icon: "fas fa-tv"
EOF
	sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
	sudo chmod -R 755 $HOMER_MODULES_DIR
else
    echo "Homer not installed — skipping"
fi


echo "Jellyfin service has been installed and configured successfully!"
