#!/bin/bash

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y nodejs npm
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm nodejs npm
fi


sudo npm install -g node-red
mkdir -p $NODE_RED_DIR

cat <<EOF | sudo tee "$NODE_RED_SERVICE" > /dev/null
[Unit]
Description=Node-red Server
After=network.target

[Service]
ExecStart=$(which node-red) --host $HOST_IP --port $NODE_RED_PORT
WorkingDirectory=$NODE_RED_DIR
User=$USER
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable --now $(basename $NODE_RED_SERVICE .service)

if command -v caddy >/dev/null 2>&1; then
    sudo tee "$NODE_RED_CADDY_CONF" > /dev/null <<EOF
https://$TS_DN:$((NODE_RED_PORT - 10000)) {
    reverse_proxy $HOST_IP:$NODE_RED_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
http://$TS_HOST:$((NODE_RED_PORT - 10001)) {
    reverse_proxy $HOST_IP:$NODE_RED_PORT
}

EOF
	sudo chown -R caddy:caddy $NODE_RED_CADDY_CONF
	sudo chmod -R 755 $NODE_RED_CADDY_CONF
else
    echo "Caddy not installed — skipping"
fi

if [ -f "$HOMER_SERVICE" ]; then
    sudo tee "$NODE_RED_HOMER_BLOCK" > /dev/null <<EOF
Secure
      - name: Node-red
        url: "https://$TS_DN:$((NODE_RED_PORT - 10000))"
        subtitle: Automation
        icon: "fas fa-project-diagram"
Unsecure
      - name: Node-red
        url: "http://$TS_HOST:$((NODE_RED_PORT - 10001))"
        subtitle: Automation
        icon: "fas fa-project-diagram"
EOF
	sudo chown -R $USER:$SERVER_GROUP "$HOMER_MODULES_DIR"
	sudo chmod -R 755 $HOMER_MODULES_DIR
else
    echo "Homer not installed — skipping"
fi

echo "Nodered service has been installed and configured successfully!"
