#!/bin/bash

source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y python3 python3-pip python3-venv build-essential ffmpeg git libpcap0.8 libpq-dev
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm
    sudo pacman -S --noconfirm python python-pip python-virtualenv base-devel ffmpeg git libpcap postgresql-libs
fi

if [ ! -d "$PYLOAD_VENV_PATH" ]; then
    $PYVER -m venv "$PYLOAD_VENV_PATH"
fi

source "$PYLOAD_VENV_PATH/bin/activate"
"$PYLOAD_VENV_PATH/bin/pip" install --upgrade pip
"$PYLOAD_VENV_PATH/bin/pip" install pyload-ng[all] beaker getch multipartposthandler safeeval bottle colorama jinja2 markupsafe pycurl setuptools thrift

mkdir -p "$PYLOAD_SCRIPT_PATH"
sudo mkdir -p "$PYLOAD_DLD_DIR"
sudo chown -R $USER:$SERVER_GROUP "$PYLOAD_DLD_DIR"
sudo find "$PYLOAD_DLD_DIR" -type f -exec chmod 660 {} \;
sudo find "$PYLOAD_DLD_DIR" -type d -exec chmod 770 {} \;

cat > "$PYLOAD_SCRIPT_PATH/pyload" <<EOL
#!/bin/bash
source "$PYLOAD_VENV_PATH/bin/activate"
exec "$PYLOAD_VENV_PATH/bin/python" -m pyload
EOL

chmod +x "$PYLOAD_SCRIPT_PATH/pyload"


sudo tee "$PYLOAD_SERVICE" > /dev/null <<EOF
[Unit]
Description=Pyload Service
After=network.target

[Service]
ExecStart=$PYLOAD_SCRIPT_PATH/pyload
User=$USER
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

cat <<EOF | sudo tee -a "$CADDY_CONF" > /dev/null
http://$TS_HOST:$((PYLOAD_PORT - 10001)) {
    reverse_proxy $HOST_IP:$PYLOAD_PORT
}

https://$TS_DN:$((PYLOAD_PORT - 10000)) {
    reverse_proxy $HOST_IP:$PYLOAD_PORT
    tls $CADDY_CERTS/$TS_DN.crt $CADDY_CERTS/$TS_DN.key
}
EOF

sudo systemctl enable --now pyload

sudo systemctl daemon-reload
sudo systemctl reload caddy
sudo systemctl restart pyload
sudo systemctl restart pyload

sed -i "s#^\([[:space:]]*folder storage_folder : \"Download folder\" =\).*#\1 $PYLOAD_DLD_DIR#" "$PYLOAD_STG_CONF"
sed -i "s#^\([[:space:]]*int port : \"Port\" =\).*#\1 $PYLOAD_PORT#" $PYLOAD_STG_CONF

sudo systemctl restart pyload

echo "pyLoad setup completed and is running as a system service."