#!/bin/sh

BASE_DIR="$HOME/.docker/hass"
CONF_DIR="$HOME/.config/home-assistant"
COMPOSE_FILE="$BASE_DIR/docker-compose.yaml"
CADDY_DIR="/etc/caddy"
mkdir -p "$BASE_DIR"
mkdir -p "$CONF_DIR"

cat > "$COMPOSE_FILE" << EOF
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - $CONF_DIR:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - "18123:8123"
EOF

cd "$BASE_DIR"
sudo docker compose up -d
PROXY_RANGE=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' homeassistant | awk -F. '{print $1"."$2".0.0/16"}')
TAILSCALE_HOST=$(tailscale status | grep $(tailscale ip -4) | awk '{print $2}')

cat <<EOF | sudo tee -a "$CONF_DIR/configuration.yaml" > /dev/null
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - $PROXY_RANGE

EOF

sudo mkdir -p $CADDY_DIR
cat <<EOF | sudo tee -a "$CADDY_DIR/Caddyfile" > /dev/null
https://$TAILSCALE_HOST:8123 {
    reverse_proxy localhost:18123
    encode gzip
    tls internal
}
EOF

sudo systemctl restart caddy
