#!/bin/bash
source ./.variables

if [ "$PACKAGE_MANAGER" == "apt" ]; then
    sudo apt update
    sudo apt install -y yarn corepack git docker docker-compose tailscale caddy jq nodejs npm
elif [ "$PACKAGE_MANAGER" == "pacman" ]; then
    sudo pacman -Syu --noconfirm yarn corepack git docker docker-compose tailscale caddy jq nodejs npm
fi

sudo systemctl enable --now {docker,tailscaled,caddy}
sudo tailscale up --ssh --auth-key="$TS_AUTH_KEY" --hostname="$HOST_NAME"
source ./.variables
sudo groupadd $SERVER_GROUP
sudo usermod -aG $SERVER_GROUP $USER
sudo mkdir -p $CADDY_CERTS
sudo rm $CADDY_CONF
sudo chown caddy:caddy $CADDY_CERTS
sudo chmod 640 $CADDY_CERTS
sudo tailscale cert $TS_DN
sudo mv $TS_DN.crt $CADDY_CERTS
sudo mv $TS_DN.key $CADDY_CERTS
sudo chown -R caddy:caddy $CADDY_CERTS
sudo chmod -R 755 $CADDY_CERTS
