#!/bin/bash
source ./.variables
MODULES=(
	"BudgetBee:modules/budgetbee"
	"Beszel Hub:modules/beszelhub"
	"Cloud Torrent:modules/cloud-torrent"
	"ESPHome:modules/esphome-pip"
	"ExpenseOwl:expenseowl"
	"FTP Server:modules/vsftpd"
	"Home Assistant:modules/hass-docker"
	"Immich:modules/immich-docker"
	"Jellyfin:modules/jellyfin"
	"Matrix Synapse:modules/synapse"
	"Music Assistant:modules/mass"
	"Paperless-ngx:modules/paperless-docker"
	"pyLoad:modules/pyload"
)

WT_LIST=()
i=1
for entry in "${MODULES[@]}"; do
	NAME="${entry%%:*}"
	WT_LIST+=("$i" "$NAME" "OFF")
	((i++))
done

NUM_ITEMS=$(( ${#WT_LIST[@]} / 3 ))
HEIGHT=$(( 8 + NUM_ITEMS ))
[ $HEIGHT -gt 25 ] && HEIGHT=25

MAXLEN=0
for ((n=1; n<${#WT_LIST[@]}; n+=3)); do
	LEN=${#WT_LIST[$n]}
	(( LEN > MAXLEN )) && MAXLEN=$LEN
done

WIDTH=$(( 20 + MAXLEN ))
[ $WIDTH -lt 50 ] && WIDTH=50
[ $WIDTH -gt 100 ] && WIDTH=100

CHOICES=$(whiptail --title "Install Wizard" --checklist \
"Select installers:" "$HEIGHT" "$WIDTH" "$NUM_ITEMS" \
"${WT_LIST[@]}" \
3>&1 1>&2 2>&3)

read -ra SELECTED <<< "$CHOICES"
SELECTED=(${SELECTED[@]//\"/})

i=1
for entry in "${MODULES[@]}"; do
	SCRIPT="${entry##*:}"
	for S in "${SELECTED[@]}"; do
		[[ "$S" == "$i" ]] && chmod +x "$SCRIPT" && bash "$SCRIPT"
	done
	((i++))
done
